# Generated by Django 5.1.6 on 2025-04-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
