# Generated by Django 5.1.6 on 2025-07-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('COD', 'Cash on Delivery')], default='ONLINE', max_length=10),
        ),
    ]
