# Generated by Django 5.1.6 on 2025-03-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryagent',
            name='location',
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='pincode',
            field=models.CharField(default=410206, max_length=10),
        ),
    ]
