# Generated by Django 5.1.6 on 2025-05-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_deliveryagent_location_deliveryagent_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
