# Generated by Django 5.1.6 on 2025-05-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_deliveryagent_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
