# Generated by Django 5.1.6 on 2025-03-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('restaurant_owner', 'Restaurant Owner'), ('delivery_agent', 'Delivery Agent'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
